[versions]
#plugins
android-gradle = "8.2.0"

# production libraries
activityComposeVersion = "1.8.2"
accompanistVersion = "0.30.1"
composeBomVersion = "2023.10.01"
coreKtxVersion = "1.12.0"
coreSplashscreenVersion = "1.0.1"
datastoreVersion = "1.0.0"
hiltVersion = "2.48"
hiltNavigationComposeVersion = "1.1.0"
kotlin = "1.9.21"
lifecycleKtxVersion = "2.6.2"
navigationVersion = "2.7.6"
retrofitVersion = "2.9.0"
roomVersion = "2.6.1"
cameraXVersion = "1.2.3"
cameraXViewVersion = "1.3.0-rc01"
coilVersion = "1.4.0"
baracodeScanerVersion = "17.2.0"
zxingVersion = "3.5.2"


[libraries]
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityComposeVersion" }
accompanist-pager = { group = "com.google.accompanist", name = "accompanist-pager", version.ref = "accompanistVersion" }
accompanist-pager-indicators = { group = "com.google.accompanist", name = "accompanist-pager-indicators", version.ref = "accompanistVersion" }
accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanistVersion" }
accompanist-permissions = {group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanistVersion"}
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBomVersion" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtxVersion" }
core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "coreSplashscreenVersion" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastoreVersion" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hiltVersion" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hiltVersion" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationComposeVersion" }
kotlin-bom = { group = "org.jetbrains.kotlin", name = "kotlin-bom", version.ref = "kotlin" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version = "lifecycleKtxVersion" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version = "lifecycleKtxVersion" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleKtxVersion" }
navigation-common = { group = "androidx.navigation", name = "navigation-common", version.ref = "navigationVersion" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationVersion" }
navigation-runtime = { group = "androidx.navigation", name = "navigation-runtime", version.ref = "navigationVersion" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofitVersion" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomVersion" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomVersion" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomVersion" }
camerax-core = {group = "androidx.camera", name = "camera-core", version.ref = "cameraXVersion"}
camerax-camera = {group = "androidx.camera", name = "camera-camera2", version.ref = "cameraXVersion"}
camerax-lifecycle = {group = "androidx.camera", name = "camera-lifecycle", version.ref = "cameraXVersion"}
camerax-view = {group = "androidx.camera", name = "camera-view", version.ref = "cameraXViewVersion"}
camerax-extensions = {group = "androidx.camera", name = "camera-extensions", version.ref = "cameraXViewVersion"}
coil = {group = "io.coil-kt", name = "coil-compose", version.ref="coilVersion"}
baracode = {group = "com.google.mlkit", name = "barcode-scanning", version.ref = "baracodeScanerVersion"}
zxing = {group = "com.google.zxing", name = "core", version.ref = "zxingVersion"}

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle" }
android-library = { id = "com.android.library", version.ref = "android-gradle" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltVersion" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
