[versions]
activityComposeVersion = "1.7.2"
androidApplicationPluginVersion = "8.1.1"
accompanistVersion = "0.30.1"
composeBomVersion = "2023.08.00"
coreKtxVersion = "1.10.1"
coreSplashscreenVersion = "1.0.1"
datastoreVersion = "1.0.0"
hiltVersion = "2.47"
hiltNavigationComposeVersion = "1.0.0"
kotlinAndroidPluginVersion = "1.8.10"
kotlinBomVersion = "1.9.0"
lifecycleKtxVersion = "2.6.1"
navigationVersion = "2.7.1"
retrofitVersion = "2.9.0"
roomVersion = "2.5.2"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
appcompat = "1.6.1"
material = "1.9.0"
org-jetbrains-kotlin-jvm = "1.8.10"
cameraXVersion = "1.2.3"
cameraXViewVersion = "1.3.0-rc01"

[libraries]
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityComposeVersion" }
accompanist-pager = { group = "com.google.accompanist", name = "accompanist-pager", version.ref = "accompanistVersion" }
accompanist-pager-indicators = { group = "com.google.accompanist", name = "accompanist-pager-indicators", version.ref = "accompanistVersion" }
accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanistVersion" }
accompanist-permissions = {group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanistVersion"}
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBomVersion" }
compose-material = { group = "androidx.compose.material", name = "material" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtxVersion" }
core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "coreSplashscreenVersion" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastoreVersion" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hiltVersion" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hiltVersion" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationComposeVersion" }
kotlin-bom = { group = "org.jetbrains.kotlin", name = "kotlin-bom", version.ref = "kotlinBomVersion" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version = "lifecycleKtxVersion" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version = "lifecycleKtxVersion" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleKtxVersion" }
navigation-common = { group = "androidx.navigation", name = "navigation-common", version.ref = "navigationVersion" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationVersion" }
navigation-runtime = { group = "androidx.navigation", name = "navigation-runtime", version.ref = "navigationVersion" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofitVersion" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomVersion" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomVersion" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
camerax-core = {group = "androidx.camera", name = "camera-core", version.ref = "cameraXVersion"}
camerax-camera = {group = "androidx.camera", name = "camera-camera2", version.ref = "cameraXVersion"}
camerax-lifecycle = {group = "androidx.camera", name = "camera-lifecycle", version.ref = "cameraXVersion"}
camerax-view = {group = "androidx.camera", name = "camera-view", version.ref = "cameraXViewVersion"}
camerax-extensions = {group = "androidx.camera", name = "camera-extensions", version.ref = "cameraXViewVersion"}


[plugins]
android-application = { id = "com.android.application", version.ref = "androidApplicationPluginVersion" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltVersion" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinAndroidPluginVersion" }
com-android-library = { id = "com.android.library", version.ref = "androidApplicationPluginVersion" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "org-jetbrains-kotlin-jvm" }
