[versions]
androidApplicationPluginVersion = "8.1.2"
accompanistVersion = "0.30.1"
cameraXVersion = "1.2.3"
cameraXMlkitVersion = "1.3.0-beta02"
coilVersion = "2.4.0"
composeBomVersion = "2023.09.00"
coreSplashscreenVersion = "1.0.1"
datastoreVersion = "1.0.0"
hiltVersion = "2.47"
hiltNavigationComposeVersion = "1.0.0"
kotlinAndroidPluginVersion = "1.8.10"
mlkitVersion = "18.0.0-beta3"
navigationVersion = "2.7.2"
retrofitVersion = "2.9.0"
roomVersion = "2.5.2"

[libraries]
accompanist-pager = { group = "com.google.accompanist", name = "accompanist-pager", version.ref = "accompanistVersion" }
accompanist-pager-indicators = { group = "com.google.accompanist", name = "accompanist-pager-indicators", version.ref = "accompanistVersion" }
accompanist-permissions = {group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanistVersion"}
accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanistVersion" }
camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "cameraXVersion" }
camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "cameraXVersion" }
camera-video = { group = "androidx.camera", name = "camera-video", version.ref = "cameraXVersion" }
camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "cameraXVersion" }
camera-mlkit = { group = "androidx.camera", name = "camera-mlkit-vision", version.ref = "cameraXMlkitVersion" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coilVersion" }
coil-gif = { group = "io.coil-kt", name = "coil-gif", version.ref = "coilVersion" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBomVersion" }
compose-material = { group = "androidx.compose.material", name = "material" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "coreSplashscreenVersion" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastoreVersion" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hiltVersion" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hiltVersion" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationComposeVersion" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version = "lifecycleKtxVersion" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version = "lifecycleKtxVersion" }
mlkit-posedetection-accurate = { group = "com.google.mlkit", name = "pose-detection-accurate", version = "18.0.0-beta3" }
navigation-common = { group = "androidx.navigation", name = "navigation-common", version.ref = "navigationVersion" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationVersion" }
navigation-runtime = { group = "androidx.navigation", name = "navigation-runtime", version.ref = "navigationVersion" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofitVersion" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "roomVersion" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomVersion" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "roomVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidApplicationPluginVersion" }
com-android-library = { id = "com.android.library", version.ref = "androidApplicationPluginVersion" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltVersion" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinAndroidPluginVersion" }