package ru.fefu.calendar_impl.domain.models

enum class TestModel {
    CLOCK_PHOTOTEST,
    FACE_PHOTOTEST,
    FULL_LENGTH_PHOTOTEST,
    HANDWRITING_PHOTOTEST,
    TESTUPDRS1ROUTE,
    TESTUPDRS2ROUTE,
    TESTUPDRS3ROUTE,
    TESTUPDRS4ROUTE,
    TESTPDQ39ROUTE,
    TESTHADSROUTE,
    TESTSCHAWABENGLANDROUTE,
    TESTHOENYAHRROUTE,
    TESTFABROUTE,
    TESTPSQIROUTE
}