package ru.fefu.calendar_impl.domain.models

enum class TestModel {
    PHOTOTEST, TESTUPDRS1ROUTE, TESTUPDRS2ROUTE, TESTUPDRS3ROUTE, TESTUPDRS4ROUTE, TESTPDQ39ROUTE,
    TESTHADSROUTE, TESTSCHAWABENGLANDROUTE,TESTHOENYAHRROUTE,TESTFABROUTE,TESTPSQIROUTE
}